name: task_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2
  flutter: "3.29.3"

dependencies:
  build_runner: ^2.4.15
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  json_serializable: ^6.9.5
  path: ^1.9.1
  skeletonizer: ^1.4.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
